# Generated by Django 2.0.6 on 2018-06-02 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receptora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='retirante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retirante', to=settings.AUTH_USER_MODEL),
        ),
    ]
